name: CI

on:
  push:
    branches: ["master"]
    tags: ["medea-*"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1


jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Vampire/setup-wsl@v1
    - run: apt get update