name: CI

on:
  push:
    branches: ["master"]
    tags: ["medea-*"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  ###########
  # Testing #
  ###########

  test-fake:
    name: Unit tests
    if: ${{ github.ref == 'refs/heads/master'
            || startsWith(github.ref, 'refs/tags/medea-')
            || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:

      - name: Deps
        run: make deps
      - name: Create
        run: make create
      
