name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make deps
      
    - name: Run check
      run: make create
    - name: Run check2
      run: make error

