name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     continue-on-error: true

#     steps:
#     - uses: actions/checkout@v3
      
#     - name: Install dependencies
#       run: make deps
      
#     - name: Run check
#       continue-on-error: true
#       run: make create

# jobs:
#   build:
#     runs-on: windows-latest
#     continue-on-error: true
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install dependencies
#       run: make deps.windows


# env:
#   CMAKE_GENERATOR: Visual Studio 16 2019
#   PYTHON_VERSION: Python39
#   NJOBS: 4

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: make try.b


# env:
#   CMAKE_GENERATOR: Visual Studio 16 2019
#   PYTHON_VERSION: Python39
#   NJOBS: 4

# jobs:
#   build:
#     runs-on: windows-latest
#     defaults:
#       run:
#         shell: cmd
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: ports\ci\windows-vs\build.bat
#     - name: Deploy
#       run: ports\ci\windows-vs\deploy.bat