name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     continue-on-error: true

#     steps:
#     - uses: actions/checkout@v3
      
#     - name: Install dependencies
#       run: make deps
      
#     - name: Run check
#       continue-on-error: true
#       run: make create

# jobs:
#   build:
#     runs-on: windows-latest
#     continue-on-error: true

#     steps:
#     - uses: actions/checkout@v2
#     - uses: msys2/setup-msys2@v2
#       with:
#         update: true
#         msystem: mingw64
#         install: >-
#           ccache
#           clang
#           cmake
#           git
#           make
#           pkgconf
#           python3
#           mingw-w64-x86_64-binutils
#           mingw-w64-i686-binutils
#           mingw-w64-x86_64-cmake
#           mingw-w64-i686-cmake
#           mingw-w64-x86_64-pkgconf
#           mingw-w64-i686-pkgconf

#     - name: Install dependencies
#       run: make deps.windows


# env:
#   CMAKE_GENERATOR: Visual Studio 16 2019
#   PYTHON_VERSION: Python39
#   NJOBS: 4

# jobs:
#   build:
#     runs-on: windows-latest
#     defaults:
#       run:
#         shell: cmd
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install dependencies
#       run: make deps.b


env:
  CMAKE_GENERATOR: Visual Studio 16 2019
  PYTHON_VERSION: Python39
  NJOBS: 4

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Build
    run: make obs
    - name: Build2
    run: regsvr32 ./bin/32bit/obs-virtualsource.dll