name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CMAKE_GENERATOR: Visual Studio 16 2019
  PYTHON_VERSION: Python39
  NJOBS: 4
  LCOW_SUPPORTED: 1

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: VirtualBox